globalThis._makeKotlinList = (arr) => {
    arr.iterator = function() {
        let i = 0;
        return {
            hasNext() { return i < arr.length ? 1 : 0; },
            next() { return arr[i++]; }
        };
    };
    arr.indexOfFirst = (pred) => arr.findIndex(pred);
    arr.removeAt     = (i)    => arr.splice(i, 1)[0];
    arr.add          = (item) => { arr.push(item); return true; };
    Object.defineProperty(arr, 'size', { get: () => arr.length, configurable: true });

    // Proxy to handle any obfuscated method name (e.g. .r(), .q(), .z())
    return new Proxy(arr, {
        get(target, prop) {
            if (prop in target) return typeof target[prop] === 'function'
                ? target[prop].bind(target)
                : target[prop];

            // Unknown prop — return a function that handles iterator/forEach patterns
            if (typeof prop === 'string') {
                return function(...args) {
                    if (typeof args[0] === 'function') { target.forEach(args[0]); return; }
                    if (args.length === 0)              return target; // iterator call
                    if (typeof args[0] === 'number')    return target[args[0]]; // get(i)
                    return target;
                };
            }
        }
    });
};

globalThis._wrapKotlinObject = function _wrapKotlinObject(obj) {
    if (obj === null || obj === undefined) return null;
    if (Array.isArray(obj)) return obj.map(_wrapKotlinObject);
    if (typeof obj !== "object") return obj;

    const keys = Object.keys(obj);
    const normalizedMap = {};
    for (const key of keys) {
        normalizedMap[String(key).toLowerCase().replace(/[_-]/g, "")] = key;
    }

    // ordered list of values for positional obfuscated access (a, b, c... l, n, o...)
    const orderedValues = keys.map(k => obj[k]);

    // build a map of single/short obfuscated names to positional values
    // obfuscated names are typically 1-2 chars: a-z, aa, ab etc.
    const obfuscatedNames = [];
    for (let i = 0; i < 26; i++) obfuscatedNames.push(String.fromCharCode(97 + i));
    for (let i = 0; i < 26; i++) for (let j = 0; j < 26; j++) obfuscatedNames.push(String.fromCharCode(97+i) + String.fromCharCode(97+j));

    return new Proxy(obj, {
        get(target, prop) {
            if (prop === Symbol.iterator) {
                const arr = Array.isArray(target) ? target : Object.values(target);
                return arr[Symbol.iterator].bind(arr.map(_wrapKotlinObject));
            }
            if (prop === "iterator") return () => {
                const arr = Array.isArray(target) ? target : Object.values(target);
                let i = 0;
                return {
                    hasNext: () => i < arr.length,
                    next: () => _wrapKotlinObject(arr[i++]),
                };
            };

            // exact match
            if (prop in target) {
                const val = target[prop];
                if (typeof val === "function") return val.bind(target);
                return () => _wrapKotlinObject(val);
            }

            // fuzzy snake_case/camelCase match
            const normalizedProp = String(prop).toLowerCase().replace(/[_-]/g, "");
            const matchedKey = normalizedMap[normalizedProp];
            if (matchedKey !== undefined) {
                const val = target[matchedKey];
                if (typeof val === "function") return val.bind(target);
                return () => _wrapKotlinObject(val);
            }

            // positional obfuscated match: l = 11th field, n = 13th etc.
            const idx = obfuscatedNames.indexOf(String(prop));
            if (idx !== -1 && idx < orderedValues.length) {
                return () => _wrapKotlinObject(orderedValues[idx]);
            }

            return () => null;
        }
    });
}

globalThis._unwrapCollection = function _unwrapCollection(col) {
    if (col == null) return [];
    if (Array.isArray(col)) return col;
    // Unwrap backing fields commonly generated by Kotlinx serialization or Kotlin/JS
    if (col._a && Array.isArray(col._a)) return col._a;
    if (col._arr && Array.isArray(col._arr)) return col._arr;
    if (col._map && typeof col._map === 'object') return Object.values(col._map);
    if (col[Symbol.iterator]) return Array.from(col);
    return [];
}

function _mutableList(items = []) {
    const arr = Array.isArray(items) ? [...items] : [...items];
    arr.add    = (item) => { arr.push(item); return true; };
    arr.addAll = (col)  => {
        const els = _unwrapCollection(col);
        for (const e of els) arr.push(e);
        return true;
    };
    arr.remove = (item) => {
        const i = arr.indexOf(item);
        if (i >= 0) { arr.splice(i, 1); return true; }
        return false;
    };
    arr.isEmpty   = () => arr.length === 0;

    Object.defineProperty(arr, 'size', {
        get() { return arr.length; },
        configurable: true
    });
    arr.get_size = () => arr.length;

    arr.contains  = (item) => arr.includes(item);
    return arr;
}
globalThis._mutableList = _mutableList;