use crate::translator::dalvik::interpreter::{JsExpr, JsStmt, RegId};

pub fn cleanup(stmts: Vec<JsStmt>) -> Vec<JsStmt> {
    let stmts = simplify_array_add(stmts);
    let stmts = simplify_first_instance(stmts);
    let stmts = simplify_foreach(stmts);
    let stmts = elide_trailing_return(stmts);
    stmts
}

fn elide_trailing_return(mut stmts: Vec<JsStmt>) -> Vec<JsStmt> {
    if matches!(stmts.last(), Some(JsStmt::Return(None))) {
        stmts.pop();
    }
    stmts
}

fn simplify_first_instance(stmts: Vec<JsStmt>) -> Vec<JsStmt> {
    let mut out = Vec::new();
    let mut i = 0;

    while i < stmts.len() {
        // Pattern 1: Iterator assignment followed immediately by the while loop
        if i + 1 < stmts.len() {
            if let (
                JsStmt::Assign { reg: _, expr: JsExpr::MethodCall { receiver: coll_expr, method: iter_method, args: iter_args, .. } },
                JsStmt::While { body, .. }
            ) = (&stmts[i], &stmts[i + 1]) {
                if iter_method == "iterator" && iter_args.is_empty() {
                    if let Some((elem_reg, class_name)) = try_rewrite_first_instance(body) {
                        // We found the collection! Emit clean JS: elem_reg = collection.firstInstance(...)
                        out.push(JsStmt::Assign {
                            reg: elem_reg.clone(),
                            expr: JsExpr::Raw(format!(
                                "{}.firstInstance(v{}_{} => v{}_{} instanceof {})",
                                expr_to_str(coll_expr),
                                elem_reg.reg,
                                elem_reg.version,
                                elem_reg.reg,
                                elem_reg.version,
                                class_name,
                            )),
                        });
                        i += 2;
                        continue;
                    }
                }
            }
        }

        // Pattern 2: Fallback (Just the loop, iterator assigned earlier or elsewhere)
        if let JsStmt::While { cond, body } = &stmts[i] {
            if let Some((elem_reg, class_name)) = try_rewrite_first_instance(body) {
                let iter_reg_str = if let Some(r) = extract_iter_reg(cond) {
                    format!("v{}_{}", r.reg, r.version)
                } else {
                    "unknown_iter".to_string()
                };

                out.push(JsStmt::Assign {
                    reg: elem_reg.clone(),
                    expr: JsExpr::Raw(format!(
                        "firstInstance({} , (v{}_{}) => v{}_{} instanceof {})",
                        iter_reg_str,
                        elem_reg.reg,
                        elem_reg.version,
                        elem_reg.reg,
                        elem_reg.version,
                        class_name,
                    )),
                });
                i += 1;
                continue;
            }
        }

        out.push(rewrite_first_instance_stmt(stmts[i].clone()));
        i += 1;
    }

    out
}

fn extract_iter_reg(cond: &JsExpr) -> Option<RegId> {
    // Navigate through `!= 0` or similar binops generated by lift.rs to find the `hasNext()` call
    match cond {
        JsExpr::BinOp { left, .. } => extract_iter_reg(left),
        JsExpr::MethodCall { receiver, .. } => {
            if let JsExpr::Reg(id) = receiver.as_ref() {
                Some(id.clone())
            } else {
                None
            }
        }
        JsExpr::Reg(id) => Some(id.clone()),
        _ => None,
    }
}

fn rewrite_first_instance_stmt(stmt: JsStmt) -> JsStmt {
    match stmt {
        JsStmt::If { cond, then_body, else_body } => JsStmt::If {
            cond,
            then_body: simplify_first_instance(then_body),
            else_body: simplify_first_instance(else_body),
        },
        JsStmt::Loop { body } => JsStmt::Loop {
            body: simplify_first_instance(body),
        },
        JsStmt::While { cond, body } => JsStmt::While {
            cond,
            body: simplify_first_instance(body),
        },
        JsStmt::Switch { expr, cases, default } => JsStmt::Switch {
            expr,
            cases: cases
                .into_iter()
                .map(|(k, v)| (k, simplify_first_instance(v)))
                .collect(),
            default: default.map(simplify_first_instance),
        },
        other => other,
    }
}

fn try_rewrite_first_instance(body: &[JsStmt]) -> Option<(RegId, String)> {
    let mut element_reg: Option<RegId> = None;
    let mut instanceof_reg: Option<RegId> = None;
    let mut class_name: Option<String> = None;

    for stmt in body {
        match stmt {
            // 1. Find the iterator.next() assignment (e.g., v9_1 = v6_5.next())
            JsStmt::Assign { reg, expr: JsExpr::MethodCall { method, args, .. } }
            if method == "next" && args.is_empty() =>
                {
                    element_reg = Some(reg.clone());
                }
            // 2. Find the instanceof check (e.g., v10_1 = v9_1 instanceof z1)
            JsStmt::Assign { reg, expr: JsExpr::BinOp { op, right, .. } }
            if op == &"instanceof" =>
                {
                    if let JsExpr::Raw(cls) = right.as_ref() {
                        instanceof_reg = Some(reg.clone());
                        class_name = Some(cls.clone());
                    }
                }
            // 3. Find the break condition (e.g., if (v10_1 !== 0) { break; })
            JsStmt::If { then_body, else_body, .. }
            if else_body.is_empty()
                && then_body.len() == 1
                && matches!(then_body[0], JsStmt::Break) =>
                {
                    // Once we have all three components, we have successfully identified the pattern.
                    if let (Some(elem), Some(_inst), Some(cls)) =
                        (&element_reg, &instanceof_reg, &class_name)
                    {
                        return Some((elem.clone(), cls.clone()));
                    }
                }
            _ => {}
        }
    }
    None
}

fn simplify_foreach(stmts: Vec<JsStmt>) -> Vec<JsStmt> {
    let mut out = Vec::new();
    let mut i = 0;

    while i < stmts.len() {
        if i + 2 < stmts.len() {
            if let Some(expr) = try_rewrite_foreach(&stmts[i], &stmts[i + 1], &stmts[i + 2]) {
                out.push(JsStmt::Expr(JsExpr::Raw(expr)));
                i += 3;
                continue;
            }
        }

        out.push(rewrite_foreach_stmt(stmts[i].clone()));
        i += 1;
    }

    out
}

fn try_rewrite_foreach(s0: &JsStmt, s1: &JsStmt, s2: &JsStmt) -> Option<String> {
    let (list_reg, list_expr) = match s0 {
        JsStmt::Assign {
            reg,
            expr: JsExpr::MethodCall { receiver, method, args, .. },
        } if args.is_empty() && method != "iterator" => {
            (reg.clone(), format!("{}.{}()", expr_to_str(receiver), method))
        }
        _ => return None,
    };

    match s1 {
        JsStmt::Assign {
            reg,
            expr: JsExpr::MethodCall { receiver, method, args, .. },
        } if *reg == list_reg
            && method == "iterator"
            && args.is_empty()
            && matches!(receiver.as_ref(), JsExpr::Reg(id) if id == &list_reg) => {}
        _ => return None,
    }

    let (item_reg, callback_stmts) = match s2 {
        JsStmt::While { cond, body } => {
            match cond {
                JsExpr::MethodCall { receiver, method, args, .. }
                if method == "hasNext"
                    && args.is_empty()
                    && matches!(receiver.as_ref(), JsExpr::Reg(id) if id == &list_reg) => {}

                // Allow un-wrapping BinOp since `!== 0` happens for conditionals
                JsExpr::BinOp { left, .. } => {
                    match left.as_ref() {
                        JsExpr::MethodCall { receiver, method, args, .. }
                        if method == "hasNext"
                            && args.is_empty()
                            && matches!(receiver.as_ref(), JsExpr::Reg(id) if id == &list_reg) => {}
                        _ => return None,
                    }
                }
                _ => return None,
            }

            if body.len() < 2 {
                return None;
            }

            let item_reg = match &body[0] {
                JsStmt::Assign {
                    reg,
                    expr: JsExpr::MethodCall { receiver, method, args, .. },
                } if method == "next"
                    && args.is_empty()
                    && matches!(receiver.as_ref(), JsExpr::Reg(id) if id == &list_reg) =>
                    {
                        reg.clone()
                    }
                _ => return None,
            };

            (item_reg, &body[1..])
        }
        _ => return None,
    };

    let body_str = if callback_stmts.len() == 1 {
        callback_stmts
            .iter()
            .map(stmt_to_str)
            .collect::<Option<Vec<_>>>()?
            .join("; ")
    } else {
        let stmts_rendered = callback_stmts
            .iter()
            .map(stmt_to_str)
            .collect::<Option<Vec<_>>>()?;
        format!("{{ {} }}", stmts_rendered.join("; "))
    };

    Some(format!(
        "{}.forEach((__item) => {{ let v{}_{} = __item; {} }})",
        list_expr, item_reg.reg, item_reg.version, body_str
    ))
}

fn expr_to_str(expr: &JsExpr) -> String {
    match expr {
        JsExpr::Reg(id) => format!("v{}_{}", id.reg, id.version),
        JsExpr::MethodCall { receiver, method, args, .. } => {
            let r = expr_to_str(receiver);
            let a = args.iter().map(expr_to_str).collect::<Vec<_>>().join(", ");
            format!("{}.{}({})", r, method, a)
        }
        JsExpr::StaticCall { class, method, args } => {
            let a = args.iter().map(expr_to_str).collect::<Vec<_>>().join(", ");
            format!("{}.{}({})", class, method, a)
        }
        JsExpr::New { class, args } => {
            let a = args.iter().map(expr_to_str).collect::<Vec<_>>().join(", ");
            format!("new {}({})", class, a)
        }
        JsExpr::FieldGet { receiver, field } => format!("{}.{}", expr_to_str(receiver), field),
        JsExpr::StaticFieldGet { class, field } => format!("{}.{}", class, field),
        JsExpr::Index { arr, idx } => format!("{}[{}]", expr_to_str(arr), expr_to_str(idx)),
        JsExpr::BinOp { op, left, right } => format!("({} {} {})", expr_to_str(left), op, expr_to_str(right)),
        JsExpr::UnaryOp { op, expr } => format!("{}{}", op, expr_to_str(expr)),
        JsExpr::BitMask { expr, mask } => format!("({} {})", expr_to_str(expr), mask),
        JsExpr::ArrayLiteral(items) => {
            let inner = items.iter().map(expr_to_str).collect::<Vec<_>>().join(", ");
            format!("[{}]", inner)
        }
        JsExpr::StringConcat(items) => {
            items.iter().map(|e| format!("String({})", expr_to_str(e))).collect::<Vec<_>>().join(" + ")
        }
        JsExpr::ThisCtorCall { args } => {
            let a = args.iter().map(expr_to_str).collect::<Vec<_>>().join(", ");
            format!("this({})", a)
        }
        JsExpr::SuperCall { args } => {
            let a = args.iter().map(expr_to_str).collect::<Vec<_>>().join(", ");
            format!("super({})", a)
        }
        JsExpr::This => "this".into(),
        // Using Rust's Debug formatter {:?} properly escapes newlines, tabs, and quotes for JS
        JsExpr::Str(s) => format!("{:?}", s),
        JsExpr::Int(n) => n.to_string(),
        JsExpr::Float(f) => f.to_string(),
        JsExpr::Bool(b) => b.to_string(),
        JsExpr::Null => "null".into(),
        JsExpr::Raw(s) => s.clone(),
        _ => "/* unhandled expr */".into(),
    }
}

fn stmt_to_str(stmt: &JsStmt) -> Option<String> {
    match stmt {
        JsStmt::Expr(e) => Some(expr_to_str(e)),
        JsStmt::Assign { reg, expr } => Some(format!(
            "v{}_{} = {}",
            reg.reg,
            reg.version,
            expr_to_str(expr)
        )),
        JsStmt::FieldSet { receiver, field, value } => Some(format!(
            "{}.{} = {}",
            expr_to_str(receiver),
            field,
            expr_to_str(value)
        )),
        JsStmt::StaticSet { class, field, value } => Some(format!(
            "{}.{} = {}",
            class,
            field,
            expr_to_str(value)
        )),
        JsStmt::ArraySet { arr, idx, value } => Some(format!(
            "{}[{}] = {}",
            expr_to_str(arr),
            expr_to_str(idx),
            expr_to_str(value)
        )),
        JsStmt::Return(Some(e)) => Some(format!("return {}", expr_to_str(e))),
        JsStmt::Return(None) => Some("return".into()),
        JsStmt::Break => Some("break".into()),
        JsStmt::Continue => Some("continue".into()),
        JsStmt::Comment(c) => Some(format!("// {}", c)),
        // Anything structurally complex (if/while/switch/try) can't easily inline into a single-line forEach
        _ => None,
    }
}

fn rewrite_foreach_stmt(stmt: JsStmt) -> JsStmt {
    match stmt {
        JsStmt::If { cond, then_body, else_body } => JsStmt::If {
            cond,
            then_body: simplify_foreach(then_body),
            else_body: simplify_foreach(else_body),
        },
        JsStmt::Loop { body } => JsStmt::Loop {
            body: simplify_foreach(body),
        },
        JsStmt::While { cond, body } => JsStmt::While {
            cond,
            body: simplify_foreach(body),
        },
        JsStmt::Switch { expr, cases, default } => JsStmt::Switch {
            expr,
            cases: cases
                .into_iter()
                .map(|(k, v)| (k, simplify_foreach(v)))
                .collect(),
            default: default.map(simplify_foreach),
        },
        other => other,
    }
}

fn simplify_array_add(stmts: Vec<JsStmt>) -> Vec<JsStmt> {
    stmts.into_iter().map(rewrite_add_stmt).collect()
}

fn rewrite_add_stmt(stmt: JsStmt) -> JsStmt {
    match stmt {
        JsStmt::Expr(expr) => JsStmt::Expr(rewrite_add_expr(expr)),
        JsStmt::Assign { reg, expr } => JsStmt::Assign {
            reg,
            expr: rewrite_add_expr(expr),
        },
        JsStmt::If { cond, then_body, else_body } => JsStmt::If {
            cond: rewrite_add_expr(cond),
            then_body: simplify_array_add(then_body),
            else_body: simplify_array_add(else_body),
        },
        JsStmt::Loop { body } => JsStmt::Loop {
            body: simplify_array_add(body),
        },
        JsStmt::While { cond, body } => JsStmt::While {
            cond: rewrite_add_expr(cond),
            body: simplify_array_add(body),
        },
        other => other,
    }
}

fn rewrite_add_expr(expr: JsExpr) -> JsExpr {
    match expr {
        JsExpr::MethodCall { receiver, method, args, is_static } if method == "add" => {
            JsExpr::MethodCall {
                receiver,
                method: "push".into(),
                args,
                is_static,
            }
        }

        JsExpr::MethodCall { receiver, method, args, .. }
        if (method == "length" || method == "size") && args.is_empty() =>
            {
                JsExpr::FieldGet {
                    receiver,
                    field: "length".into(),
                }
            }

        other => other,
    }
}
